apiVersion: v1
kind: ReplicationController
metadata:
  name: inspircd-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inspircd
    spec:
      containers:
      - name: inspircd
        image: verb/inspircd-k8s:latest
        ports:
        - containerPort: 6697
        volumeMounts:
          - name: inspircd-config
            mountPath: /etc/inspircd
      volumes:
        - name: inspircd-config
          secret:
            secretName: inspircd-secrets
